server:
  port: "8000" # API 服务监听的端口

logger:
  mode: "dev"            # dev 或 prod
  level: "debug"         # debug/info/warn/error
#  path: "./pkg/logger/app.log"   # 日志文件路径
  max_size: 100          # 单文件最大 MB
  max_backups: 7         # 保留旧文件数
  max_age: 30            # 保留天数
  compress: true         # 是否压缩

# 数据库配置
database:
  host: "localhost"
  port: 5432
  user: "src_hunter"      # 你的 PostgreSQL 用户名
  password: "123.com" # 你的 PostgreSQL 密码
  dbname: "src_hunter_db"     # 数据库名称
  sslmode: "disable"    # 暂时在自己的开发环境禁用SSL

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0